### ISSUE TITLE
StaticInjectorError in angular 8 project

### ISSUE THREAD

**Issue by bigfish** [ionic-team/stencil-ds-plugins#34]
Hello. I originally posted this issue in the demo project repo, but have not got any response in a week, so thought I would also post it here, since I believe it actually an issue with the plugin.

see https://github.com/ionic-team/stencil-ds-plugins-demo/issues/14

Steps to Repro:

1. Clone repo: https://github.com/ionic-team/stencil-ds-plugins-demo
2. npm install
3. lerna bootstrap
4. build component-library
5. build component-library-angular
6. 'npm start' app-angular
7. Open http://localhost:4200 in Chrome (80)

See following error in console (twice)

AppComponent.html:3 ERROR NullInjectorError: StaticInjectorError(AppModule)[DemoComponent -> ChangeDetectorRef]:
StaticInjectorError(Platform: core)[DemoComponent -> ChangeDetectorRef]:
NullInjectorError: No provider for ChangeDetectorRef!
at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (http://localhost:4200/vendor.js:89853:25)
at resolveToken (http://localhost:4200/vendor.js:101046:24)
at tryResolveToken (http://localhost:4200/vendor.js:100990:16)
at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (http://localhost:4200/vendor.js:100892:20)
at resolveToken (http://localhost:4200/vendor.js:101046:24)
at tryResolveToken (http://localhost:4200/vendor.js:100990:16)
at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (http://localhost:4200/vendor.js:100892:20)
at resolveNgModuleDep (http://localhost:4200/vendor.js:109362:29)
at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (http://localhost:4200/vendor.js:110033:16)
at resolveDep (http://localhost:4200/vendor.js:110404:45)

**Comment by Paul-Hebert** [comment]
Hey @bigfish , did you ever get this working? I'm trying to use this with Angular 9 and running into a number of problems. I wonder if there are compatibility issues between this and newer Angular versions?

**Comment by Paul-Hebert** [comment]
I tried this with Angular 7 (as that's what the demo project repo uses) but am still getting a StaticInjectorError error. I'll update if I learn more.

**Comment by Paul-Hebert** [comment]
@bigfish I was able to fix this by adding this to `/packages/app-angular/tsconfig.json` in the `compilerOptions` section:

```
    "paths": {
      "@angular/*": [
          "node_modules/@angular/*"
      ],
    }
```

Though I'm using Angular 7. I'm still getting some other issues I'm trying to work through.

**Comment by bigfish** [comment]
thanks, @Paul-Hebert, I'll give that a try!

**Comment by bigfish** [comment]
ok, yes, that does resolve the issue for me as well. Guess I will close this now.

**Comment by Paul-Hebert** [comment]
Glad to hear that fixed it!
